input_data_path: 'ml_project/data/raw/heart_cleveland_upload.csv'
output_model_path: 'ml_project/models/model.pkl'
metric_path: 'ml_project/models/metrics.json'
splitting_params:
  val_size: 0.2
  random_state: 0
training_params:
  model_type: 'RandomForestClassifier'
  model_params:
    n_estimators: 100
feature_params:
  categorical_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'oldpeak'
  features_to_drop:
    - 'thalach'
  special_feature:
    - 'oldpeak'
  target_col: 'condition'
  