apiVersion: v1
kind: Pod
metadata:
  name: online-inference-health
  labels:
    app: online-inference-health
spec:
  containers:
    - image: oriolus1/hw2:v2
      name: online-inference
      ports:
        - containerPort: 8000
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 180
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 3